spring:
  profiles:
    active:
    - dev #当前使用的环境
---
content: dev content 刷新
spring:
  profiles: dev
  application:
    name: config-server
------
content: test content 刷新
spring:
  profiles: dev
  application:
    name: config-server